# Generated by Django 5.2.1 on 2026-06-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('issuer', models.CharField(blank=True, max_length=160, verbose_name='برگزارکننده')),
                ('instructor', models.CharField(blank=True, max_length=120, verbose_name='مدرس')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='سال')),
                ('hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='ساعت')),
                ('category', models.CharField(choices=[('backend', 'بک\u200cاند'), ('ai_data', 'هوش مصنوعی و داده'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته')),
                ('url', models.URLField(blank=True, verbose_name='لینک مدرک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='تصویر مدرک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه\u200cها',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=160, verbose_name='عنوان شغلی')),
                ('organization', models.CharField(max_length=160, verbose_name='سازمان')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='مکان')),
                ('period', models.CharField(help_text='متن نمایشی، مثلاً: خرداد ۱۴۰۲ – اکنون', max_length=120, verbose_name='بازه\u200cی زمانی')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع (برای مرتب\u200cسازی)')),
                ('is_current', models.BooleanField(default=False, verbose_name='شغل فعلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'تجربه\u200cی کاری',
                'verbose_name_plural': 'تجربه\u200cهای کاری',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام کامل')),
                ('headline', models.CharField(help_text='مثلاً: مهندس بک\u200cاند پایتون و هوش مصنوعی', max_length=160, verbose_name='عنوان شغلی')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='شعار کوتاه')),
                ('about', models.TextField(blank=True, verbose_name='درباره\u200cی من')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='محل سکونت')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='تلفن')),
                ('show_phone', models.BooleanField(default=False, verbose_name='نمایش عمومی تلفن')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='عکس')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='فایل رزومه')),
                ('available_for_work', models.BooleanField(default=True, verbose_name='آماده\u200cی همکاری')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام مهارت')),
                ('level', models.PositiveSmallIntegerField(default=3, verbose_name='سطح (۱ تا ۵)')),
                ('featured', models.BooleanField(default=True, help_text='اگر خاموش باشد فقط به\u200cعنوان تگ پروژه استفاده می\u200cشود.', verbose_name='نمایش در بخش مهارت\u200cها')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=90, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='کلاس آیکن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته\u200cی مهارت',
                'verbose_name_plural': 'دسته\u200cهای مهارت',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='عنوان')),
                ('url', models.URLField(verbose_name='لینک')),
                ('icon', models.CharField(blank=True, help_text='مثلاً: fab fa-github', max_length=60, verbose_name='کلاس آیکن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'لینک اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای اجتماعی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True, verbose_name='اسلاگ')),
                ('summary', models.CharField(max_length=255, verbose_name='خلاصه\u200cی یک\u200cخطی')),
                ('problem', models.TextField(blank=True, verbose_name='مشکل')),
                ('solution', models.TextField(blank=True, verbose_name='راه\u200cحل')),
                ('outcome', models.TextField(blank=True, verbose_name='نتیجه')),
                ('category', models.CharField(choices=[('ai', 'هوش مصنوعی'), ('backend', 'بک\u200cاند'), ('data', 'داده'), ('web', 'وب')], default='backend', max_length=20, verbose_name='دسته')),
                ('status', models.CharField(choices=[('completed', 'تکمیل\u200cشده'), ('in_progress', 'در حال توسعه')], default='completed', max_length=20, verbose_name='وضعیت')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='تصویر کاور')),
                ('github_url', models.URLField(blank=True, verbose_name='لینک گیت\u200cهاب')),
                ('live_url', models.URLField(blank=True, verbose_name='لینک زنده')),
                ('is_private', models.BooleanField(default=False, verbose_name='پروژه\u200cی خصوصی (بدون افشای کد)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='شاخص')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='my_cv.skill', verbose_name='تک\u200cاستک')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order', '-is_featured'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='my_cv.skillcategory', verbose_name='دسته'),
        ),
    ]
